# -*- coding: utf-8 -*-
"""Master configuration: the single source of all tunable parameters.

Import via `from config import CONFIG` and read e.g. `CONFIG.simulation.days`.
Sensitive values (API keys) may be overridden through environment variables.
"""

import os

# Fall back to a mirror for HuggingFace downloads; a user-provided HF_ENDPOINT wins.
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")

import datetime
from dataclasses import dataclass, field
from pathlib import Path
from typing import Tuple

PROJECT_ROOT = Path(__file__).resolve().parent
CASE_DIR = PROJECT_ROOT / "case"

# Case registry: each case lists its companion files explicitly.
CASE_REGISTRY = {
    "nanjing": {
        "net_file": CASE_DIR / "nanjing_nodes" / "37nodes.net.xml",
        "taz_file": CASE_DIR / "nanjing_nodes" / "37nodes.taz.xml",
        "type_file": CASE_DIR / "nanjing_nodes" / "37nodes_taz_type.txt",
        "station_file": CASE_DIR / "nanjing_nodes" / "37nodes.cs.price.xml",
        "grid_file": CASE_DIR / "nanjing_nodes" / "37nodes.grid.xml",
        "fcs_file": CASE_DIR / "nanjing_nodes" / "37nodes.fcs.xml",
        "scs_file": CASE_DIR / "nanjing_nodes" / "37nodes.scs.xml",
        "agents_file": CASE_DIR / "nanjing_nodes" / "37nodes_agents.json",
        "npcs_file": CASE_DIR / "nanjing_nodes" / "37nodes_npcs.json",
    },
    "12nodes": {
        "net_file": CASE_DIR / "12nodes" / "12nodes.net.xml",
        "taz_file": CASE_DIR / "12nodes" / "12nodes.taz.xml",
        "type_file": CASE_DIR / "12nodes" / "taz_type.txt",
        "station_file": CASE_DIR / "12nodes" / "12nodes.cs.price.xml",
        "grid_file": CASE_DIR / "12nodes" / "pdn.grid.xml",
        "fcs_file": CASE_DIR / "12nodes" / "12nodes.fcs.xml",
        "scs_file": CASE_DIR / "12nodes" / "12nodes.scs.xml",
        "agents_file": CASE_DIR / "12nodes" / "agents.json",
        "npcs_file": CASE_DIR / "12nodes" / "npcs.json",
    },
}
DEFAULT_CASE = "12nodes"


@dataclass
class PathConfig:
    case_name: str = DEFAULT_CASE

    # Paths below are populated in __post_init__ from CASE_REGISTRY.
    net_file: str = ""
    taz_file: str = ""
    type_file: str = ""
    station_file: str = ""   # generated by overwrite_prices.py
    grid_file: str = ""
    fcs_file: str = ""       # input when generating prices
    scs_file: str = ""       # input when generating prices
    agents_file: str = ""
    npcs_file: str = ""

    archetypes_file: str = str(CASE_DIR / "archetypes.json")
    results_dir: str = str(PROJECT_ROOT / "results")
    chroma_db: str = str(PROJECT_ROOT / "chroma_db")
    sumo_log: str = str(PROJECT_ROOT / "sumo_error.log")

    def __post_init__(self):
        info = CASE_REGISTRY.get(self.case_name)
        if info is None:
            raise ValueError(
                f"Unknown road network case: {self.case_name!r}, available: {sorted(CASE_REGISTRY)}"
            )
        for key, path in info.items():
            setattr(self, key, str(path))


@dataclass
class SecretsConfig:
    deepseek_api_key: str = os.environ.get("DEEPSEEK_API_KEY")
    deepseek_base_url: str = os.environ.get(
        "DEEPSEEK_BASE_URL", "https://api.deepseek.com"
    )
    google_api_key: str = os.environ.get("GOOGLE_API_KEY")


@dataclass
class SimulationConfig:
    days: int = 1                      # simulation days
    step_minutes: int = 1              # simulation step (minutes)
    start_hour: int = 6                # daily start (06:00)
    end_hour: int = 24                 # daily end (24:00)
    base_date: datetime.date = field(
        default_factory=lambda: datetime.date(2025, 5, 20)
    )
    max_api_concurrency: int = 5       # max concurrent LLM calls (lower on 429)
    sumo_gui: bool = False             # False = headless (faster)
    sumo_step_length: float = 1.0      # SUMO step length (seconds)
    sumo_max_end_time: int = 86400 * 100  # keep SUMO alive, do not exit
    sumo_waiting_time_memory: int = 1000  # SUMO deadlock protection window


@dataclass
class VehicleConfig:
    capacity_kwh: float = 75.0         # Tesla Model Y Long Range
    max_charge_power_kw: float = 250.0 # max fast-charge power
    max_slow_power_kw: float = 11.0    # max slow-charge power
    car_model: str = "Tesla Model Y"
    length_m: float = 4.8
    width_m: float = 2.0
    min_gap_m: float = 2.5


@dataclass
class StationConfig:
    fcs_max_power_kw: float = 120.0    # fast charger hardware power
    scs_max_power_kw: float = 10.0     # slow charger hardware power
    default_slots: int = 10            # default slots when XML omits it
    wait_time_factor: float = 30.0     # est. wait = (queue/slots) * factor (min)
    fcs_full_soc: float = 0.95         # FCS "full" threshold (auto unplug)


@dataclass
class GridConfig:
    sb_mva: float = 1.0                # base power (MVA), XML may override
    ub_kv: float = 10.0                # base voltage (kV)
    v_safe: float = 0.98               # below this, prices start rising
    v_critical: float = 0.92           # below this, exponential surge zone
    price_linear_high: float = 3.0     # upper multiplier of the linear zone
    price_max: float = 10.0            # multiplier cap
    price_surge_exp: float = 10.0      # exponential penalty in the danger zone
    price_history_len: int = 5         # moving-average filter window (minutes)
    limit_slope: float = 10.0          # load-limiting P-controller slope
    limit_floor: float = 0.1           # minimum retained power ratio
    broadcast_cooldown_s: int = 1800   # news broadcast cooldown (seconds)
    price_surge_threshold: float = 3.0 # multiplier threshold for PRICE_SURGE
    grid_alert_voltage: float = 0.88   # voltage threshold for GRID_ALERT
    intuition_critical: float = 0.92   # intuition: CRITICAL OVERLOAD boundary
    intuition_heavy: float = 0.96      # intuition: HEAVY LOAD boundary


@dataclass
class SolverConfig:
    tan_phi: float = 0.328             # tan(arccos(0.95)) ~= 0.328
    u_min: float = 0.25                # U = V^2 lower bound (V >= 0.5 p.u.)
    collapse_v_min: float = 0.5        # voltage collapse lower bound
    collapse_v_max: float = 1.5        # voltage collapse upper bound
    fallback_voltage: float = 0.85     # fallback voltage on solver failure
    solver_name: str = "ECOS"          # cvxpy solver (ECOS / OSQP)


@dataclass
class AgentConfig:
    # Physical consumption
    consumption_per_km: float = 0.005  # SoC per km (0.5% / km)
    survival_buffer: float = 0.02      # absolute survival reserve (2%)
    base_consumption_per_min: float = 0.0001  # per-minute base (A/C, onboard)
    drive_consumption_scale: float = 1.3       # kinetic consumption correction

    # Comfort / panic thresholds
    comfort_base: float = 0.05         # base comfort buffer
    comfort_anxiety_scale: float = 0.15    # comfort buffer anxiety coefficient
    comfort_anxiety_scale_alt: float = 0.10  # slightly lower for Layer-3 scenarios
    panic_base: float = 0.30           # base panic threshold
    panic_anxiety_scale: float = 0.50  # panic threshold anxiety coefficient
    panic_gig_offset: float = 0.10     # gig-worker panic bonus
    panic_sensitive_offset: float = -0.05  # price-sensitive panic reduction
    driving_discount: float = 0.8      # panic threshold discount while driving

    # Emergence point: the wealthy want "full" below this SoC
    insensitive_emerge_soc: float = 0.40

    # Price perception
    price_tolerance_base: float = 1.5      # base price tolerance
    price_tolerance_scale: float = 0.4     # price tolerance sensitivity
    bargain_threshold: float = 0.9         # below this multiplier = BARGAIN

    # Time perception
    slight_late_min: int = 15              # slight lateness threshold (min)
    dist_to_go_default_km: float = 10.0    # default distance when IDLE

    # Curfew (no thinking deep at night)
    curfew_start_hour: int = 0
    curfew_end_hour: int = 6

    # Expectation-violation detection
    price_surprise_tolerance: float = 0.1  # arrival price surge tolerance ($)
    queue_surprise_extra: int = 2          # queue worsening by N cars = worse

    # Utility weights
    w_time_base: float = 1.0
    w_time_commuter: float = 3.0
    w_time_gig: float = 1.5
    w_money_base: float = 1.0
    w_money_sensitive: float = 3.0
    w_money_insensitive: float = 0.5
    w_anxiety_base: float = 1.0
    w_anxiety_anxious: float = 3.0
    w_anxiety_calm: float = 0.8

    # Utility coefficients
    u_time_per_min: float = -1.0           # penalty per minute late
    u_cost_per_dollar: float = -2.0        # penalty per dollar
    u_soc_critical_scale: float = -50.0    # penalty per 1% below 20% SoC
    u_soc_climb: float = 1.0               # reward per 1% in 20%-50% band
    u_soc_saturated: float = 30.0          # fixed reward above 50%
    u_gain_per_kwh: float = 5.0            # reward per kWh charged

    # Utility evaluation label thresholds
    eval_failure: float = -100.0
    eval_regret: float = -30.0
    eval_acceptable: float = 20.0

    # Price psychological anchors
    price_anchor_new: float = 0.8          # weight of the new price
    price_anchor_old: float = 0.2          # weight of the old anchor
    initial_history_avg_price: float = 1.0 # initial price prior

    # Schedule adjustment (5 min / unit)
    schedule_shift_unit_min: int = 5


@dataclass
class NPCConfig:
    max_daily_trips_default: int = 2   # commuter max daily trips
    consumption_rate_default: float = 0.01
    capacity_kwh: float = 60.0
    fcs_full_soc: float = 0.95


@dataclass
class MemoryConfig:
    alpha_recency: float = 1.0         # retrieval weight: recency
    beta_importance: float = 1.0       # retrieval weight: importance
    gamma_relevance: float = 1.0       # retrieval weight: relevance
    reflection_threshold: int = 100    # accumulated importance triggering reflection
    snapshot_storage_threshold: int = 4  # snapshots below this are not stored
    recent_buffer_maxlen: int = 50     # recent-memory buffer size
    decay_factor: float = 0.99         # recency decay (per hour)
    default_top_k: int = 3             # default retrieval count
    reflect_model: str = "gemini-2.0-flash-lite"  # Gemini model for reflection


@dataclass
class StorageConfig:
    embedding_model: str = "all-MiniLM-L6-v2"           # local embedding model
    scorer_model: str = "cross-encoder/ms-marco-TinyBERT-L-2-v2"  # importance scorer
    collection_name: str = "global_memory_space"        # Chroma collection name
    hnsw_space: str = "cosine"                          # similarity metric


@dataclass
class LLMConfig:
    deepseek_model: str = "deepseek-chat"
    deepseek_temperature: float = 0.7
    deepseek_retries: int = 3
    deepseek_request_interval_s: float = 0.1  # delay after each call
    deepseek_backoff_base_s: float = 2.0      # retry backoff base
    use_mock_llm: bool = False               # True = mock returns (debug only)

    gemini_model: str = "gemini-2.5-flash"

    # Retrieval channels
    retrieve_similar_top_k: int = 2      # similar-episode channel
    retrieve_trauma_top_k: int = 2       # trauma channel
    retrieve_critical_top_k: int = 1     # critical-snapshot channel
    critical_snapshot_importance: int = 8  # min importance of a critical snapshot


@dataclass
class GenerationConfig:
    agents_seed: int = 42
    instances_per_archetype: int = 4    # instances per archetype (8 archetypes x N)
    force_new_archetypes: bool = False  # True = regenerate archetypes via LLM
    initial_soc_min: float = 0.25       # initial SoC lower bound
    initial_soc_max: float = 0.75       # initial SoC upper bound

    # Qualitative -> quantitative mapping ranges
    sensitive_price_range: Tuple[float, float] = (0.75, 1.0)
    insensitive_price_range: Tuple[float, float] = (0.0, 0.25)
    anxious_range: Tuple[float, float] = (0.7, 1.0)
    calm_range: Tuple[float, float] = (0.0, 0.3)

    # Safety buffers (minutes)
    anxious_safety_buffer: Tuple[int, int] = (5, 10)
    calm_safety_buffer: Tuple[int, int] = (0, 5)

    # Physical duration estimation
    speed_noise_sigma: float = 3.0      # Gaussian noise std (km/h)
    speed_floor: float = 10.0           # minimum speed
    overhead_min: Tuple[int, int] = (2, 5)  # parking/start base time

    npcs_count: int = 10000
    npcs_seed: int = 42
    npc_commuter_ratio: float = 0.7     # commuter share
    npc_cheapest_ratio: float = 0.5     # CHEAPEST strategy share
    npc_soc_min: float = 0.2
    npc_soc_max: float = 0.65
    npc_commuter_first_depart: Tuple[int, int] = (7, 8)   # work 7:00-8:59
    npc_commuter_return: Tuple[int, int, int, int] = (16, 18, 30, 30)  # leave 16:30-18:30
    npc_gig_first_depart: Tuple[int, int] = (6, 6)        # gig 6:00-6:59
    npc_gig_max_trips: Tuple[int, int] = (20, 25)
    npc_consumption_rate: Tuple[float, float] = (0.015, 0.025)
    npc_path_check_attempts: int = 50   # connectivity retry attempts


@dataclass
class PricingConfig:
    # Format: (start hour, price multiplier), must cover 0-24h in order.
    profiles: dict = field(default_factory=lambda: {
        "HOME": [(0, 0.5), (7, 1.0), (22, 0.5)],   # residential: off-peak benefit
        "WORK": [(0, 1.0), (8, 1.5), (17, 1.0)],   # workplace: daytime penalty
        "FCS": [(0, 1.5), (8, 3.0), (10, 2.0), (17, 3.0), (20, 1.5)],  # public fast: peak penalty
    })
    fcs_psell: float = 0.5             # FCS V2G buy-back (FCS usually no V2G)
    scs_psell: float = 1.0             # SCS V2G buy-back


@dataclass
class PipelineConfig:
    generate_prices: bool = True        # stage 1: pricing XML
    generate_agents: bool = True        # stage 2: agents (incl. archetypes)
    generate_npcs: bool = True          # stage 3: NPCs
    simulate: bool = True               # stage 4: simulation


@dataclass
class AblationConfig:
    # Decision-engine baseline (run.py --baseline):
    #   "full"      = dual-system (System-1 rules + System-2 LLM), default.
    #   "event_llm" = event-triggered LLM (no cognitive state machine).
    #   "mnl"       = conventional MNL discrete choice (fully non-LLM).
    baseline_mode: str = "full"

    # A. Event-triggered baseline: strip the cognitive-state mechanism,
    #    keep "event trigger + LLM decision" only.
    baseline_no_cognitive_state: bool = False

    # B. FSM / Pydantic constraint ablation.
    disable_pydantic_validation: bool = False
    disable_fsm_intercept: bool = False

    # C. Persona vs numeric-parameter ablation.
    uniform_persona: bool = False
    uniform_numeric_params: bool = False

    # Fixed persona used when uniform_persona=True.
    uniform_persona_role: str = "COMMUTER"
    uniform_persona_price_trait: str = "SENSITIVE"
    uniform_persona_anxiety_trait: str = "ANXIOUS"

    # Fixed numeric params used when uniform_numeric_params=True.
    uniform_anxiety_level: float = 0.5
    uniform_price_sensitivity: float = 0.5
    uniform_param_role: str = "COMMUTER"
    uniform_param_price_trait: str = "SENSITIVE"
    uniform_param_anxiety_trait: str = "ANXIOUS"

    # D. Memory ablation: True disables loading/retrieval/write/reflection.
    #    Default True (no memory); enable with `run.py --memory`.
    disable_memory: bool = True


@dataclass
class MNLConfig:
    # Utility: U_i = -beta_time*t_i - beta_price*p_i - beta_distance*d_i,
    #   where t_i = wait (min) + travel (distance/avg_speed*60).
    beta_time: float = 0.5        # time cost per minute
    beta_price: float = 30.0      # price cost per $/kWh
    beta_distance: float = 1.0    # distance cost per km
    anxiety_time_scale: float = 1.0         # beta_time *= (1 + anxiety * scale)
    price_sensitivity_scale: float = 1.0    # beta_price *= (1 + sensitivity * scale)
    avg_speed_kmh: float = 30.0   # assumed urban average speed (km/h)
    temperature: float = 1.0      # softmax temperature (lower = closer to argmax)


@dataclass
class Config:
    paths: PathConfig = field(default_factory=PathConfig)
    secrets: SecretsConfig = field(default_factory=SecretsConfig)
    simulation: SimulationConfig = field(default_factory=SimulationConfig)
    vehicle: VehicleConfig = field(default_factory=VehicleConfig)
    station: StationConfig = field(default_factory=StationConfig)
    grid: GridConfig = field(default_factory=GridConfig)
    solver: SolverConfig = field(default_factory=SolverConfig)
    agent: AgentConfig = field(default_factory=AgentConfig)
    npc: NPCConfig = field(default_factory=NPCConfig)
    memory: MemoryConfig = field(default_factory=MemoryConfig)
    storage: StorageConfig = field(default_factory=StorageConfig)
    llm: LLMConfig = field(default_factory=LLMConfig)
    generation: GenerationConfig = field(default_factory=GenerationConfig)
    pricing: PricingConfig = field(default_factory=PricingConfig)
    pipeline: PipelineConfig = field(default_factory=PipelineConfig)
    ablation: AblationConfig = field(default_factory=AblationConfig)
    mnl: MNLConfig = field(default_factory=MNLConfig)

    def describe(self) -> str:
        """Print the full current configuration (for experiment reproducibility)."""
        lines = ["=" * 70, "Current experiment configuration (CONFIG)", "=" * 70]
        for section in [
            "paths", "simulation", "vehicle", "station", "grid", "solver", "agent",
            "npc", "memory", "storage", "llm", "generation", "pipeline",
            "ablation", "mnl",
        ]:
            lines.append(f"\n[{section}]")
            sec = getattr(self, section)
            for k, v in sec.__dict__.items():
                lines.append(f"  {k} = {v!r}")
        lines.append("=" * 70)
        return "\n".join(lines)


CONFIG = Config()


def _apply_env_overrides():
    """Bridge command-line args (passed via DUALSYS_* env vars) into CONFIG."""
    def _int(name):
        v = os.environ.get(name)
        return int(v) if v is not None else None

    def _bool(name):
        v = os.environ.get(name)
        return (v == "1") if v is not None else None

    if os.environ.get("DUALSYS_CASE"):
        CONFIG.paths.case_name = os.environ.get("DUALSYS_CASE")
        CONFIG.paths.__post_init__()

    if _int("DUALSYS_DAYS") is not None:
        CONFIG.simulation.days = _int("DUALSYS_DAYS")
    if _bool("DUALSYS_GUI") is not None:
        CONFIG.simulation.sumo_gui = _bool("DUALSYS_GUI")
    if _int("DUALSYS_CONCURRENCY") is not None:
        CONFIG.simulation.max_api_concurrency = _int("DUALSYS_CONCURRENCY")
    if _int("DUALSYS_NPCS") is not None:
        CONFIG.generation.npcs_count = _int("DUALSYS_NPCS")
    if _int("DUALSYS_SEED") is not None:
        CONFIG.generation.agents_seed = _int("DUALSYS_SEED")
        CONFIG.generation.npcs_seed = _int("DUALSYS_SEED")
    if _int("DUALSYS_INSTANCES") is not None:
        CONFIG.generation.instances_per_archetype = _int("DUALSYS_INSTANCES")
    if _bool("DUALSYS_FORCE_NEW") is not None:
        CONFIG.generation.force_new_archetypes = _bool("DUALSYS_FORCE_NEW")
    if _bool("DUALSYS_NO_COG") is not None:
        CONFIG.ablation.baseline_no_cognitive_state = _bool("DUALSYS_NO_COG")
    if _bool("DUALSYS_NO_PYDANTIC") is not None:
        CONFIG.ablation.disable_pydantic_validation = _bool("DUALSYS_NO_PYDANTIC")
    if _bool("DUALSYS_NO_FSM") is not None:
        CONFIG.ablation.disable_fsm_intercept = _bool("DUALSYS_NO_FSM")
    if _bool("DUALSYS_UNIFORM_PERSONA") is not None:
        CONFIG.ablation.uniform_persona = _bool("DUALSYS_UNIFORM_PERSONA")
    if _bool("DUALSYS_UNIFORM_PARAMS") is not None:
        CONFIG.ablation.uniform_numeric_params = _bool("DUALSYS_UNIFORM_PARAMS")
    if _bool("DUALSYS_NO_MEMORY") is not None:
        CONFIG.ablation.disable_memory = _bool("DUALSYS_NO_MEMORY")

    bm = os.environ.get("DUALSYS_BASELINE")
    if bm:
        CONFIG.ablation.baseline_mode = bm
    if CONFIG.ablation.baseline_mode != "full":
        CONFIG.ablation.baseline_no_cognitive_state = True


_apply_env_overrides()


if __name__ == "__main__":
    print(CONFIG.describe())
