import xml.etree.ElementTree as ET
from xml.dom import minidom
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import CONFIG


# Pricing profiles: (start hour, price); must cover 0-24h in chronological order.
PROFILES = CONFIG.pricing.profiles


def get_project_root():
    """Return the project root (this script lives under scripts/)."""
    return Path(__file__).resolve().parent.parent


def parse_taz_types(file_path):
    """Parse taz_type.txt -> {'TAZ1': 'Home', ...}."""
    taz_map = {}
    if not os.path.exists(file_path):
        print(f"⚠️ Warning: {file_path} not found. All zones will be 'Other'.")
        return taz_map

    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or ':' not in line:
                continue
            type_name, taz_ids = line.split(':')
            type_name = type_name.strip()
            for tid in taz_ids.split(','):
                taz_map[tid.strip()] = type_name
    return taz_map


def parse_edge_to_taz(file_path):
    """Parse 12nodes.taz.xml -> {'gneE1': 'TAZ1', ...}."""
    edge_map = {}
    if not os.path.exists(file_path):
        print(f"⚠️ Warning: {file_path} not found. Cannot map edges to zones.")
        return edge_map

    tree = ET.parse(file_path)
    root = tree.getroot()
    for taz in root.findall('taz'):
        t_id = taz.get('id')
        for child in taz:
            if child.tag in ['tazSource', 'tazSink']:
                edge_id = child.get('id')
                edge_map[edge_id] = t_id
    return edge_map


def generate_pbuy_element(profile_name):
    """Generate a single-day (24h) <pbuy> node; the simulator wraps it with time % 86400."""
    pbuy = ET.Element('pbuy')

    schedule = PROFILES.get(profile_name, PROFILES["WORK"])

    for hour, price in schedule:
        btime = hour * 3600

        item = ET.SubElement(pbuy, 'item')
        item.set('btime', str(btime))
        item.set('price', str(price))

    return pbuy


def prettify(elem):
    """Pretty-print XML."""
    rough_string = ET.tostring(elem, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ")


def main():
    root_dir = get_project_root()
    case_dir = root_dir / "case"

    print("🗺️  Building region mapping...")
    taz_type_map = parse_taz_types(CONFIG.paths.type_file)
    edge_taz_map = parse_edge_to_taz(CONFIG.paths.taz_file)

    def get_zone_type(edge_id):
        taz_id = edge_taz_map.get(edge_id)
        if taz_id:
            return taz_type_map.get(taz_id, "Other")
        return "Other"

    # FCS and SCS are merged under one root.
    output_root = ET.Element('root')
    output_root.set('description', 'Research-Grade Pricing Generated by Script')

    fcs_file = Path(CONFIG.paths.fcs_file)
    if fcs_file.exists():
        print(f"⚡ Processing fast chargers (FCS) from {fcs_file.name}...")
        tree = ET.parse(fcs_file)
        for fcs in tree.getroot().findall('fcs'):
            new_fcs = ET.SubElement(output_root, 'fcs')
            for k, v in fcs.attrib.items():
                new_fcs.set(k, v)

            new_fcs.set('station_class', 'FCS_Public')

            new_fcs.append(generate_pbuy_element("FCS"))

            # FCS typically has no V2G buy-back.
            psell = ET.SubElement(new_fcs, 'psell')
            ET.SubElement(psell, 'item', btime="0", price=str(CONFIG.pricing.fcs_psell))

    scs_file = Path(CONFIG.paths.scs_file)
    if scs_file.exists():
        print(f"🔋 Processing slow chargers (SCS) from {scs_file.name}...")
        tree = ET.parse(scs_file)
        for scs in tree.getroot().findall('scs'):
            new_scs = ET.SubElement(output_root, 'scs')
            for k, v in scs.attrib.items():
                new_scs.set(k, v)

            edge_id = scs.get('edge')
            zone_type = get_zone_type(edge_id)

            if zone_type == "Home":
                profile_name = "HOME"
                desc = "Home_SCS_Profile_A"
            elif zone_type == "Work":
                profile_name = "WORK"
                desc = "Work_SCS_Profile_B"
            else:
                profile_name = "WORK"
                desc = "Other_SCS_Profile_B"

            new_scs.set('zone_type', zone_type)
            new_scs.set('pricing_profile', desc)

            new_scs.append(generate_pbuy_element(profile_name))

            # SCS supports V2G; buy-back is fixed here.
            psell = ET.SubElement(new_scs, 'psell')
            ET.SubElement(psell, 'item', btime="0", price=str(CONFIG.pricing.scs_psell))

    output_path = Path(CONFIG.paths.station_file)
    print(f"💾 Writing to: {output_path}")

    xml_str = prettify(output_root)

    with open(output_path, "w", encoding='utf-8') as f:
        f.write(xml_str)

    print("✅ Done! The generated pricing file now includes differentiated pricing for Home/Work/FCS.")
    print("👉 Make sure to load this new file in station_manager.py, or copy its contents back over the original fcs/scs.xml.")


if __name__ == "__main__":
    main()
